# Change these first
owner: gomasy # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: API (REST) / Web UI
    url: https://don.gomasy.jp/health
  - name: API (Streaming)
    url: https://don.gomasy.jp/api/v1/streaming/health
  - name: Object Storage
    url: https://m.gmsy.in/health/ready
  - name: E-mail
    url: mail.gomasy.jp
    port: 25
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gomasy.jp
  # baseUrl: /
  logoUrl: https://don.gomasy.jp/media/icons/android-chrome-256x256.png
  name: status.gomasy.jp
  introTitle: "Status page of [ごま丼](https://don.gomasy.jp/about)"

workflowSchedule:
  updates: "0 0 1 1 *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
